import MySQLdb

db = MySQLdb.connect("572b2568442c7.sh.cdb.myqcloud.com", "cdb_outerroot", "software2015", "dracarys",
                     port=8161, charset="utf8")
cursor = db.cursor()
# cursor.execute('delete from `stock_2016` where `date` <= "2015-12-31"')
# db.commit()
# cursor.execute('update `stock_2015` set `dif` = 0 where `dif` is null')
# cursor.execute('update `stock_2015` set `dea` = 0 where `dea` is null')
# cursor.execute('update `stock_2015` set `macd` = 0 where `macd` is null')
# cursor.execute('update `stock_2015` set `boll_upper` = 0 where `boll_upper` is null')
# cursor.execute('update `stock_2015` set `boll_middle` = 0 where `boll_middle` is null')
# cursor.execute('update `stock_2015` set `boll_low` = 0 where `boll_low` is null')
# cursor.execute('update `stock_2015` set `slowK` = 0 where `slowK` is null')
# cursor.execute('update `stock_2015` set `slowD` = 0 where `slowD` is null')
# cursor.execute('update `stock_2015` set `slowJ` = 0 where `slowJ` is null')
# cursor.execute('update `stock_2015` set `ma5` = 0 where `ma5` is null')
# cursor.execute('update `stock_2015` set `ma10` = 0 where `ma10` is null')
# cursor.execute('update `stock_2015` set `ma20` = 0 where `ma20` is null')
# cursor.execute('update `stock_2015` set `ma30` = 0 where `ma30` is null')
# cursor.execute('update `stock_2015` set `ma60` = 0 where `ma60` is null')
# cursor.execute('update `stock_2015` set `atr` = 0 where `atr` is null')
# cursor.execute('update `stock_2015` set `rsi6` = 0 where `rsi6` is null')
# cursor.execute('update `stock_2015` set `rsi12` = 0 where `rsi12` is null')
# cursor.execute('update `stock_2015` set `rsi24` = 0 where `rsi24` is null')
# cursor.execute('update `stock_2016` set dif = 0')
# cursor.execute('update `stock_2016` set dea = 0')
# cursor.execute('update `stock_2016` set macd = 0')
cursor.execute('delete from `stock_2016` where `date` = "2016-08-11"')
# cursor.execute('select * from `short_ticks` where `date` = "2016-0"')
print cursor.fetchall()